name: Deploy to Local Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Vue.js app
      run: |
        cp /var/www/quhousefinder.com/.env .env
        cd frontend
        npm install
        npm run build

    - name: Deploy frontend files
      run: |
        rsync -av --delete frontend/dist/ /var/www/quhousefinder.com/frontend

    - name: Deploy backend files
      run: |
        rsync -av --delete backend/ /var/www/quhousefinder.com/backend
        cd /var/www/quhousefinder.com/backend && npm install

    - name: Restart backend service
      run: |
        pm2 restart api-server
